#ifndef EVENTS_DB_H
#define EVENTS_DB_H

#include <stdint.h>
#include <stddef.h>

/* Embedded event->sample database (events_db.bin), generated by
 * tools/gen_events_db.py from the FMOD bank JSON manifests.
 *
 * It lets the loader build the event->sample mapping natively (without
 * shipping the JSON manifest files at runtime).  Format (little-endian):
 *   uint32 num_banks
 *   repeated num_banks times:
 *     uint32 bankname_len; bytes bankname (base name, no ".bank")
 *     uint32 num_events
 *     repeated num_events times:
 *       uint32 path_len;  bytes path  (event:/...)
 *       uint32 file_len;  bytes file  (sample filename == FSB5 name)
 */

struct event_entry {
	const char *path;   /* event:/... path (lookup key) */
	const char *file;   /* sample filename (== FSB5 sample name) */
};

struct bank_events {
	const char *bankname;          /* base name, e.g. "sfx" */
	uint32_t count;
	struct event_entry *entries;   /* sorted by path for binary search */
};

/* Locate the embedded database entry for a bank by base name.
 * Returns 1 and fills *out on success, 0 if the bank is not in the DB. */
int events_db_find(const char *bankname, struct bank_events *out);

/* Free the entry array allocated by events_db_find(). */
void events_db_free(struct bank_events *be);

#endif
